version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://93.127.194.118:9020/api
        VITE_APP_NAME: "Sabka Placement"
    container_name: sabkaplacement-frontend
    restart: unless-stopped
    ports:
      - "9021:9021"
      